import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {randomUUID} from 'node:crypto';
import {JSDOM} from 'jsdom';
const html=await readFile('public/index.html','utf8');
const data=await readFile('public/benchmarks.js','utf8');
const app=await readFile('public/app.js','utf8');
function setup(){const dom=new JSDOM(html,{url:'https://ussu-suni.pages.dev',runScripts:'outside-only'});const w=dom.window;Object.defineProperty(w.crypto,'randomUUID',{value:randomUUID});w.HTMLDialogElement.prototype.showModal=function(){this.open=true;};w.HTMLDialogElement.prototype.close=function(){this.open=false;};w.scrollTo=()=>{};w.eval(data+'\n'+app);return dom;}
test('benchmark metrics remain separate; search and open-weight filtering work',()=>{const dom=setup(),w=dom.window,d=w.document;try{assert.equal(d.querySelectorAll('.model-row').length,8);d.querySelector('[data-metric="arena"]').click();assert.match(d.querySelector('#metric-title').textContent,/Arena/);assert.equal(d.querySelectorAll('.model-row').length,7);d.querySelector('#model-access').value='open';d.querySelector('#model-access').dispatchEvent(new w.Event('change'));assert.equal(d.querySelectorAll('.model-row').length,3);d.querySelector('#model-search').value='olmayan model';d.querySelector('#model-search').dispatchEvent(new w.Event('input'));assert.equal(d.querySelectorAll('.model-row').length,0);assert.match(d.querySelector('#benchmark-list').textContent,/eşleşme yok/);}finally{dom.window.close();}});
test('contribution records default to no training permission and never expose user text as HTML',()=>{const dom=setup(),w=dom.window,d=w.document;try{d.querySelector('[data-action="compose"]').click();d.querySelector('#draft-title').value='<img src=x onerror=alert(1)>';d.querySelector('#draft-prompt').value='Eksik bilgi içeren örnek görev';d.querySelector('#draft-observed').value='Model sayı uydurdu';d.querySelector('#draft-body').value='Başlangıç değeri verilmediği için kesin sayı söylememelidir.';d.querySelector('#compose-form').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));const saved=JSON.parse(w.localStorage.getItem('ussu-suni-preview-v1')).drafts[0];assert.equal(saved.permissions.training,'deny');assert.equal(saved.learningEligibility,'denied');assert.equal(saved.status,'unverified-draft');assert.equal(saved.proposedRoute,'skill-candidate');assert.equal(d.querySelectorAll('#dialog-body img').length,0);assert.equal(d.querySelectorAll('#dialog-body a[href*="issues/new"]').length,0);assert.match(d.querySelector('#dialog-body').textContent,/<img src=x/);}finally{dom.window.close();}});
test('source tasks require evidence and high-risk contributions are routed to specialist review',()=>{const dom=setup(),w=dom.window,d=w.document;try{d.querySelector('[data-action="compose"]').click();d.querySelector('#draft-type').value='source';d.querySelector('#draft-type').dispatchEvent(new w.Event('change'));assert.equal(d.querySelector('#draft-source').required,true);assert.equal(d.querySelector('#draft-evidence').required,true);assert.equal(d.querySelector('#evidence-details').open,true);d.querySelector('#draft-title').value='Yüksek riskli iddia';d.querySelector('#draft-prompt').value='Kaynak doğru mu?';d.querySelector('#draft-body').value='Bu iddia uzman tarafından kontrol edilmelidir.';d.querySelector('#draft-source').value='https://example.org/';d.querySelector('#draft-evidence').value='Yalnızca kontrol örneği, doğrulanmış kaynak değil.';d.querySelector('#draft-risk').value='high';d.querySelector('#compose-form').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));const saved=JSON.parse(w.localStorage.getItem('ussu-suni-preview-v1')).drafts[0];assert.equal(saved.proposedRoute,'specialist-review');assert.equal(saved.permissions.publicReview,false);}finally{dom.window.close();}});

test('task entry selects the right contribution type and private preferences cannot produce public submission links',()=>{const dom=setup(),w=dom.window,d=w.document;try{d.querySelector('[data-task="source"]').click();assert.equal(d.querySelector('#draft-type').value,'source');d.querySelector('#draft-type').value='preference';d.querySelector('#draft-type').dispatchEvent(new w.Event('change'));d.querySelector('#draft-title').value='Tercih test kaydı';d.querySelector('#draft-prompt').value='Örnek görev';d.querySelector('#draft-observed').value='Örnek yanıt';d.querySelector('#draft-body').value='Bu yalnızca kişisel alanda kalması gereken bir tercihtir.';d.querySelector('#draft-public').checked=true;d.querySelector('#draft-safe').checked=true;d.querySelector('#compose-form').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));assert.equal(d.querySelectorAll('#dialog-body a[href*="issues/new"]').length,0);const saved=JSON.parse(w.localStorage.getItem('ussu-suni-preview-v1')).drafts[0];assert.equal(saved.proposedRoute,'personal-only');}finally{dom.window.close();}});
