import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {randomUUID} from 'node:crypto';
import {JSDOM} from 'jsdom';
const html=await readFile('public/index.html','utf8');
const data=await readFile('public/benchmarks.js','utf8');
const app=await readFile('public/app.js','utf8');
const game=await readFile('public/game.js','utf8');
function setup(saved){const dom=new JSDOM(html,{url:'https://ussu-suni.pages.dev',runScripts:'outside-only'});const w=dom.window;Object.defineProperty(w.crypto,'randomUUID',{value:randomUUID});w.HTMLDialogElement.prototype.showModal=function(){this.open=true;};w.HTMLDialogElement.prototype.close=function(){this.open=false;};w.scrollTo=()=>{};if(saved)w.localStorage.setItem('ussu-suni-preview-v1',JSON.stringify(saved));w.eval(data+'\n'+app+'\n'+game+'\nwindow.gameTest={stats:gameStats,day:dayKey,reward:rewardDraft,state};');return dom;}
test('benchmark metrics remain separate; search and open-weight filtering work',()=>{const dom=setup(),w=dom.window,d=w.document;try{assert.equal(d.querySelectorAll('.model-row').length,8);d.querySelector('[data-metric="arena"]').click();assert.match(d.querySelector('#metric-title').textContent,/Arena/);assert.equal(d.querySelectorAll('.model-row').length,7);d.querySelector('#model-access').value='open';d.querySelector('#model-access').dispatchEvent(new w.Event('change'));assert.equal(d.querySelectorAll('.model-row').length,3);d.querySelector('#model-search').value='olmayan model';d.querySelector('#model-search').dispatchEvent(new w.Event('input'));assert.equal(d.querySelectorAll('.model-row').length,0);assert.match(d.querySelector('#benchmark-list').textContent,/eşleşme yok/);}finally{dom.window.close();}});
test('contribution records default to no training permission and never expose user text as HTML',()=>{const dom=setup(),w=dom.window,d=w.document;try{d.querySelector('[data-action="compose"]').click();d.querySelector('#draft-title').value='<img src=x onerror=alert(1)>';d.querySelector('#draft-prompt').value='Eksik bilgi içeren örnek görev';d.querySelector('#draft-observed').value='Model sayı uydurdu';d.querySelector('#draft-body').value='Başlangıç değeri verilmediği için kesin sayı söylememelidir.';d.querySelector('#compose-form').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));const saved=JSON.parse(w.localStorage.getItem('ussu-suni-preview-v1')).drafts[0];assert.equal(saved.permissions.training,'deny');assert.equal(saved.learningEligibility,'denied');assert.equal(saved.status,'unverified-draft');assert.equal(saved.proposedRoute,'skill-candidate');assert.equal(d.querySelectorAll('#dialog-body img').length,0);assert.equal(d.querySelectorAll('#dialog-body a[href*="issues/new"]').length,0);assert.match(d.querySelector('#dialog-body').textContent,/<img src=x/);}finally{dom.window.close();}});
test('source tasks require evidence and high-risk contributions are routed to specialist review',()=>{const dom=setup(),w=dom.window,d=w.document;try{d.querySelector('[data-action="compose"]').click();d.querySelector('#draft-type').value='source';d.querySelector('#draft-type').dispatchEvent(new w.Event('change'));assert.equal(d.querySelector('#draft-source').required,true);assert.equal(d.querySelector('#draft-evidence').required,true);assert.equal(d.querySelector('#evidence-details').open,true);d.querySelector('#draft-title').value='Yüksek riskli iddia';d.querySelector('#draft-prompt').value='Kaynak doğru mu?';d.querySelector('#draft-body').value='Bu iddia uzman tarafından kontrol edilmelidir.';d.querySelector('#draft-source').value='https://example.org/';d.querySelector('#draft-evidence').value='Yalnızca kontrol örneği, doğrulanmış kaynak değil.';d.querySelector('#draft-risk').value='high';d.querySelector('#compose-form').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));const saved=JSON.parse(w.localStorage.getItem('ussu-suni-preview-v1')).drafts[0];assert.equal(saved.proposedRoute,'specialist-review');assert.equal(saved.permissions.publicReview,false);}finally{dom.window.close();}});

test('task entry selects the right contribution type and private preferences cannot produce public submission links',()=>{const dom=setup(),w=dom.window,d=w.document;try{d.querySelector('[data-task="source"]').click();assert.equal(d.querySelector('#draft-type').value,'source');d.querySelector('#draft-type').value='preference';d.querySelector('#draft-type').dispatchEvent(new w.Event('change'));d.querySelector('#draft-title').value='Tercih test kaydı';d.querySelector('#draft-prompt').value='Örnek görev';d.querySelector('#draft-observed').value='Örnek yanıt';d.querySelector('#draft-body').value='Bu yalnızca kişisel alanda kalması gereken bir tercihtir.';d.querySelector('#draft-public').checked=true;d.querySelector('#draft-safe').checked=true;d.querySelector('#compose-form').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));assert.equal(d.querySelectorAll('#dialog-body a[href*="issues/new"]').length,0);const saved=JSON.parse(w.localStorage.getItem('ussu-suni-preview-v1')).drafts[0];assert.equal(saved.proposedRoute,'personal-only');}finally{dom.window.close();}});
function answer(d,n){d.querySelector(`[data-answer="${n}"]`).click();d.querySelector('#lesson-check').click();d.querySelector('#lesson-next').click();}
function completeFirst(d){d.querySelector('[data-lesson="language"]').click();for(const n of [1,0,2])answer(d,n);}
test('lessons require correct answers, unlock the next stop and award XP only once',()=>{const dom=setup(),w=dom.window,d=w.document;try{assert.equal(d.querySelector('[data-lesson="uncertainty"]').disabled,true);d.querySelector('[data-lesson="language"]').click();answer(d,0);assert.match(d.querySelector('#dialog-title').textContent,/önbelleğe/);assert.equal(w.gameTest.stats().xp,0);for(const n of [1,0,2])answer(d,n);assert.equal(w.gameTest.stats().xp,20);assert.equal(w.gameTest.stats().todayCount,1);assert.equal(d.querySelector('[data-lesson="uncertainty"]').disabled,false);completeFirst(d);assert.equal(w.gameTest.stats().xp,20);assert.equal(w.gameTest.stats().todayCount,1);assert.match(d.querySelector('#dialog-title').textContent,/tekrar/);}finally{w.close();}});
test('progress resumes after reload, goals persist and drafts earn XP independently of training permission',()=>{const dom=setup(),w=dom.window,d=w.document;let resumed;try{d.querySelector('[data-lesson="language"]').click();answer(d,1);d.querySelector('#daily-goal-select').value='2';d.querySelector('#daily-goal-select').dispatchEvent(new w.Event('change'));const saved=JSON.parse(w.localStorage.getItem('ussu-suni-preview-v1'));resumed=setup(saved);const rw=resumed.window,rd=rw.document;rd.querySelector('.game-continue').click();assert.match(rd.querySelector('#dialog-title').textContent,/Etekleri/);assert.equal(rd.querySelector('#daily-goal-select').value,'2');rd.querySelector('[data-action="compose"]').click();rd.querySelector('#draft-title').value='İlk yerel katkı';rd.querySelector('#draft-prompt').value='Kısa açıkla';rd.querySelector('#draft-observed').value='Uzun yanıt';rd.querySelector('#draft-body').value='İstenen uzunluk sınırı da ayrı değerlendirilmelidir.';rd.querySelector('#compose-form').dispatchEvent(new rw.Event('submit',{bubbles:true,cancelable:true}));const after=JSON.parse(rw.localStorage.getItem('ussu-suni-preview-v1'));assert.equal(after.drafts[0].permissions.training,'deny');assert.equal(rw.gameTest.stats().xp,10);rw.gameTest.reward();assert.equal(rw.gameTest.stats().xp,10);}finally{w.close();resumed?.window.close();}});
test('daily streak uses Istanbul days, tolerates a break and ignores malformed persisted dates',()=>{const dom=setup({saved:[],drafts:[],evaluations:{},game:{completed:['language'],practice:{'2026-10-07':['language'],'2026-10-08':['language'],'2026-99-99':['language'],'2026-02-31':['language']},session:{id:'permissions',step:1}}}),w=dom.window;try{assert.equal(w.gameTest.stats('2026-10-09').streak,2);assert.equal(w.gameTest.stats('2026-10-10').streak,0);assert.equal(w.gameTest.stats('2026-10-10').xp,20);assert.equal(w.gameTest.day(new Date('2026-10-08T21:01:00Z')),'2026-10-09');assert.equal(w.gameTest.state.game.practice['2026-02-31'],undefined);assert.equal(w.gameTest.state.game.session,null);}finally{w.close();}});
